source "https://github.com/TaranWu/Go23WalletSpec.git"
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!
platform :ios, '13.0'

target 'Go23WalletAddress_Example' do
  pod 'Go23WalletAddress', :path => '../'
  
  target 'Go23WalletAddress_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['LD_NO_PIE'] = 'NO'
          config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            
            if ['Result'].include? target.name
              target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.2'
              end
            end
      end
  end
end
