use_frameworks!

platform :ios, '10.0'

target 'Go23WalletAddress_Example' do
  pod 'Go23WalletAddress', :path => '../'

  target 'Go23WalletAddress_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
